Generator: use a pointer before unmarshalling into non-pointer structs (#707)
# Description
<!--
* Prefix: the title with the component name being changed. Add a short
and self describing sentence to ease the review
* Please add a few lines providing context and describing the change
* Please self comment changes whenever applicable to help with the
review process
* Please keep the checklist as part of the PR. Tick what applies to this
change.
-->

Some calls would fail at the generated client would try to unmarshall
into using the struct and not a pointer to the struct. example:

```
error: error retrieving deprecated resources: ListSKSClusterDeprecatedResources: prepare Json response: json: Unmarshal(non-pointer []v3.SKSClusterDeprecatedResource)
```

This fixes that.

## Checklist
(For exoscale contributors)

* [x] Changelog updated (under *Unreleased* block)
* [x] For a new resource or new attributes: test added/updated


Tested that with this change, the call unmarshals correctly